name: Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '17'

      - name: Install dependencies
        run: npm ci

#       - name: Build Angular project
#         run: npm run build -- --configuration production

#       - name: Clean remote directory
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: deployer
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             rm -rf /var/www/html/*

#       - name: Deploy via SSH
#         uses: appleboy/scp-action@master
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: deployer
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           source: "dist/angular-sales/browser/*"
#           target: "/var/www/angular.raphp.net"

#       - name: Reload Apache
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: deployer
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             sudo systemctl reload apache2







      - name: Build production
        run: npm run build -- --configuration production

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: deployer
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/angular-sales/browser/*"
          target: "/var/www/angular.raphp.net"

      - name: Reload Apache
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: deployer
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: sudo systemctl reload apache2
